name: tmp-22-p5
channels:
  - conda-forge
  - maxibor
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - datasets
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - numba>=0.55
  - scikit-learn
  - seaborn
  - pytest
  - pyhamcrest
  - plotly
  - python-graphviz
  - llvmlite
  - llvmdev
  - tslearn
  - pip
  - pip:
    - stumpy # doesn't work if conda-forge installed, gives error Numba needs NumPy 1.20 or less even when forcing numba >0.55
