name: tmp-22
channels:
  - conda-forge
  - maxibor
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - datasets
  - numpy
  - matplotlib
  - seaborn
  - pandas=1.4 # in pandas 1.5 the DataFrame.resample / first methods work differently and drop the original time_col in the resampled df which produces different results and number of days, fixing this for reproducibility of the paper
  - numba>=0.55
  - scikit-learn
  - seaborn
  - pytest
  - pyhamcrest
  - plotly
  - python-graphviz
  - llvmlite
  - llvmdev
  - tslearn
  - pip
  - pip:
    - stumpy # doesn't work if conda-forge installed, gives error Numba needs NumPy 1.20 or less even when forcing numba >0.55
