name: tmp-22
channels:
  - conda-forge
  - maxibor
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - datasets
  - numpy
  - matplotlib
  - pandas
  - numba>=0.55
  - scikit-learn
  - seaborn
  - wandb # experiment mgr
  - pytest
  - pyhamcrest
  - plotly
#  - sktime   # gives conflicts -> move to pip
#  - tsfresh # gives conflicts -> move to pip
  - pip
  - pip:
##    - matrixprofile -> doesn't work on M1 max
    - stumpy # doesn't work if conda-forge installed, gives error Numba needs NumPy 1.20 or less even when forcing numba >0.55